version: '3'


services:
  docs:
    build: docs
    expose:
      - 80

  frontend:
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/frontend:rw
      - frontend-dist:/frontend/application/dist:rw

  backend:
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8000
    env_file:
      - .env.dev
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./server/licensing:/app/licensing

  nginx:
    build: nginx/dev
    ports:
      # - 8000:80
      - 80:80
    links:
      - docs
      - backend
      - frontend
    volumes:
      - ./files:/files:ro
      - ./server/licensing:/app:ro
      - frontend-dist:/app/server_main/static/js:ro

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    volumes:
      - ./tmp/db:/var/lib/mysql

  wordpress:
    image: wordpress
    # ports:
    #   - 8080:80
    env_file:
      - .env.dev
    volumes:
      - ./tmp/wordpress:/var/www/html
      - ./wordpress-plugin-licenses-server:/var/www/html/wp-content/plugins/licenses-server


volumes:
  frontend-dist: