FROM nginx:alpine

# COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY ./certs/www.diamondfms.com.crt /etc/nginx/ssl/www.diamondfms.com.crt
# COPY ./certs/www.diamondfms.com.key /etc/nginx/ssl/www.diamondfms.com.key

EXPOSE 80
EXPOSE 443
